// Code generated by protoc-gen-go. DO NOT EDIT.
// source: es_map_proto3.proto

package test

import (
	fmt "fmt"
	proto1 "git.zapa.cloud/merchant-tools/helper/proto"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/tvducmt/protoc-gen-toEs/protobuf"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// `TransStatus` is status of a transaction
type TransStatus int32

const (
	TransStatus_TS_UNSPECIFIED TransStatus = 0
	TransStatus_TS_FAIL        TransStatus = 1
	TransStatus_TS_SUCCESSFUL  TransStatus = 2
	TransStatus_TS_ALL         TransStatus = 3
	TransStatus_TS_NEW         TransStatus = 4
)

var TransStatus_name = map[int32]string{
	0: "TS_UNSPECIFIED",
	1: "TS_FAIL",
	2: "TS_SUCCESSFUL",
	3: "TS_ALL",
	4: "TS_NEW",
}

var TransStatus_value = map[string]int32{
	"TS_UNSPECIFIED": 0,
	"TS_FAIL":        1,
	"TS_SUCCESSFUL":  2,
	"TS_ALL":         3,
	"TS_NEW":         4,
}

func (x TransStatus) String() string {
	return proto.EnumName(TransStatus_name, int32(x))
}

func (TransStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1bdf614473d9b62, []int{0}
}

type TransactionMessage3_TransChargeStatus int32

const (
	TransactionMessage3_TCS_UNSPECIFIED TransactionMessage3_TransChargeStatus = 0
	TransactionMessage3_TCS_PAID        TransactionMessage3_TransChargeStatus = 1
	TransactionMessage3_TCS_UNPAID      TransactionMessage3_TransChargeStatus = 2
	TransactionMessage3_TCS_PENDING     TransactionMessage3_TransChargeStatus = 3
)

var TransactionMessage3_TransChargeStatus_name = map[int32]string{
	0: "TCS_UNSPECIFIED",
	1: "TCS_PAID",
	2: "TCS_UNPAID",
	3: "TCS_PENDING",
}

var TransactionMessage3_TransChargeStatus_value = map[string]int32{
	"TCS_UNSPECIFIED": 0,
	"TCS_PAID":        1,
	"TCS_UNPAID":      2,
	"TCS_PENDING":     3,
}

func (x TransactionMessage3_TransChargeStatus) String() string {
	return proto.EnumName(TransactionMessage3_TransChargeStatus_name, int32(x))
}

func (TransactionMessage3_TransChargeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1bdf614473d9b62, []int{0, 0}
}

// `DataTransLog` represents data will be reported as table on client in all trasactions.
type TransactionMessage3 struct {
	// @inject_tag: es:"reqDate"
	CreateTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ToDate     *proto1.Date         `protobuf:"bytes,2,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	// // @inject_tag: es:"pmcName"
	PmcName        string `protobuf:"bytes,3,opt,name=pmc_name,json=pmcName,proto3" json:"pmc_name,omitempty"`
	DiscountAmount int64  `protobuf:"varint,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	// @inject_tag: es:"transErrCode"
	TransCode string `protobuf:"bytes,5,opt,name=trans_code,json=transCode,proto3" json:"trans_code,omitempty"`
	// @inject_tag: es:"transChargeStatus"
	TransChargeStatus TransactionMessage3_TransChargeStatus `protobuf:"varint,6,opt,name=trans_charge_status,json=transChargeStatus,proto3,enum=test.TransactionMessage3_TransChargeStatus" json:"trans_charge_status,omitempty"`
	MerchantName      string                                `protobuf:"bytes,7,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	UserInfo          *TransactionMessage3_UserInfo         `protobuf:"bytes,8,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	// // // @inject_tag: es:"companyInfo"
	CompanyInfo          *TransactionMessage3_CompanyInfo `protobuf:"bytes,9,opt,name=company_info,json=companyInfo,proto3" json:"company_info,omitempty"`
	ItemCount            int32                            `protobuf:"varint,10,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *TransactionMessage3) Reset()         { *m = TransactionMessage3{} }
func (m *TransactionMessage3) String() string { return proto.CompactTextString(m) }
func (*TransactionMessage3) ProtoMessage()    {}
func (*TransactionMessage3) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1bdf614473d9b62, []int{0}
}

func (m *TransactionMessage3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionMessage3.Unmarshal(m, b)
}
func (m *TransactionMessage3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionMessage3.Marshal(b, m, deterministic)
}
func (m *TransactionMessage3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionMessage3.Merge(m, src)
}
func (m *TransactionMessage3) XXX_Size() int {
	return xxx_messageInfo_TransactionMessage3.Size(m)
}
func (m *TransactionMessage3) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionMessage3.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionMessage3 proto.InternalMessageInfo

func (m *TransactionMessage3) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *TransactionMessage3) GetToDate() *proto1.Date {
	if m != nil {
		return m.ToDate
	}
	return nil
}

func (m *TransactionMessage3) GetPmcName() string {
	if m != nil {
		return m.PmcName
	}
	return ""
}

func (m *TransactionMessage3) GetDiscountAmount() int64 {
	if m != nil {
		return m.DiscountAmount
	}
	return 0
}

func (m *TransactionMessage3) GetTransCode() string {
	if m != nil {
		return m.TransCode
	}
	return ""
}

func (m *TransactionMessage3) GetTransChargeStatus() TransactionMessage3_TransChargeStatus {
	if m != nil {
		return m.TransChargeStatus
	}
	return TransactionMessage3_TCS_UNSPECIFIED
}

func (m *TransactionMessage3) GetMerchantName() string {
	if m != nil {
		return m.MerchantName
	}
	return ""
}

func (m *TransactionMessage3) GetUserInfo() *TransactionMessage3_UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *TransactionMessage3) GetCompanyInfo() *TransactionMessage3_CompanyInfo {
	if m != nil {
		return m.CompanyInfo
	}
	return nil
}

func (m *TransactionMessage3) GetItemCount() int32 {
	if m != nil {
		return m.ItemCount
	}
	return 0
}

type TransactionMessage3_UserInfo struct {
	// @inject_tag: es:"email" query:"*%*"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// @inject_tag: es:"phoneNumber" query:"*%*"
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	// @inject_tag: es:"address"
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionMessage3_UserInfo) Reset()         { *m = TransactionMessage3_UserInfo{} }
func (m *TransactionMessage3_UserInfo) String() string { return proto.CompactTextString(m) }
func (*TransactionMessage3_UserInfo) ProtoMessage()    {}
func (*TransactionMessage3_UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1bdf614473d9b62, []int{0, 0}
}

func (m *TransactionMessage3_UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionMessage3_UserInfo.Unmarshal(m, b)
}
func (m *TransactionMessage3_UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionMessage3_UserInfo.Marshal(b, m, deterministic)
}
func (m *TransactionMessage3_UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionMessage3_UserInfo.Merge(m, src)
}
func (m *TransactionMessage3_UserInfo) XXX_Size() int {
	return xxx_messageInfo_TransactionMessage3_UserInfo.Size(m)
}
func (m *TransactionMessage3_UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionMessage3_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionMessage3_UserInfo proto.InternalMessageInfo

func (m *TransactionMessage3_UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *TransactionMessage3_UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *TransactionMessage3_UserInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type TransactionMessage3_CompanyInfo struct {
	// @inject_tag: es:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// @inject_tag: es:"shortName"
	ShortName            string                        `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	UserInf              *TransactionMessage3_UserInfo `protobuf:"bytes,3,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *TransactionMessage3_CompanyInfo) Reset()         { *m = TransactionMessage3_CompanyInfo{} }
func (m *TransactionMessage3_CompanyInfo) String() string { return proto.CompactTextString(m) }
func (*TransactionMessage3_CompanyInfo) ProtoMessage()    {}
func (*TransactionMessage3_CompanyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1bdf614473d9b62, []int{0, 1}
}

func (m *TransactionMessage3_CompanyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionMessage3_CompanyInfo.Unmarshal(m, b)
}
func (m *TransactionMessage3_CompanyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionMessage3_CompanyInfo.Marshal(b, m, deterministic)
}
func (m *TransactionMessage3_CompanyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionMessage3_CompanyInfo.Merge(m, src)
}
func (m *TransactionMessage3_CompanyInfo) XXX_Size() int {
	return xxx_messageInfo_TransactionMessage3_CompanyInfo.Size(m)
}
func (m *TransactionMessage3_CompanyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionMessage3_CompanyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionMessage3_CompanyInfo proto.InternalMessageInfo

func (m *TransactionMessage3_CompanyInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TransactionMessage3_CompanyInfo) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *TransactionMessage3_CompanyInfo) GetUserInf() *TransactionMessage3_UserInfo {
	if m != nil {
		return m.UserInf
	}
	return nil
}

func init() {
	proto.RegisterEnum("test.TransStatus", TransStatus_name, TransStatus_value)
	proto.RegisterEnum("test.TransactionMessage3_TransChargeStatus", TransactionMessage3_TransChargeStatus_name, TransactionMessage3_TransChargeStatus_value)
	proto.RegisterType((*TransactionMessage3)(nil), "test.TransactionMessage3")
	proto.RegisterType((*TransactionMessage3_UserInfo)(nil), "test.TransactionMessage3.UserInfo")
	proto.RegisterType((*TransactionMessage3_CompanyInfo)(nil), "test.TransactionMessage3.CompanyInfo")
}

func init() { proto.RegisterFile("es_map_proto3.proto", fileDescriptor_d1bdf614473d9b62) }

var fileDescriptor_d1bdf614473d9b62 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5f, 0x8b, 0xeb, 0x44,
	0x14, 0x37, 0xfb, 0x2f, 0xcd, 0xc9, 0xb6, 0x4d, 0xa7, 0x82, 0xa1, 0x20, 0xc6, 0x05, 0xb1, 0x28,
	0x9b, 0xe2, 0xbd, 0x8a, 0xf8, 0xe0, 0xc3, 0x36, 0xdb, 0x4a, 0xa1, 0xc6, 0x25, 0x49, 0xb9, 0x88,
	0x0f, 0x61, 0x9a, 0xcc, 0xb6, 0x81, 0x4e, 0x26, 0x37, 0x33, 0x11, 0xae, 0x9f, 0xc2, 0xaf, 0xe1,
	0xd7, 0xc8, 0x43, 0x3e, 0x97, 0x64, 0x26, 0x71, 0xd7, 0x7b, 0x5d, 0xf0, 0x69, 0xce, 0xef, 0x77,
	0xce, 0xf9, 0xcd, 0xe4, 0xfc, 0x0e, 0x81, 0x29, 0xe1, 0x31, 0xc5, 0x45, 0x5c, 0x94, 0x4c, 0xb0,
	0xd7, 0xae, 0x3c, 0xd0, 0x85, 0x20, 0x5c, 0xcc, 0xbe, 0x3b, 0x64, 0xc2, 0xfd, 0x03, 0x17, 0xd8,
	0x4d, 0x4e, 0xac, 0x4a, 0x17, 0x94, 0x94, 0xc9, 0x11, 0xe7, 0xe2, 0x56, 0x30, 0x76, 0xe2, 0x8b,
	0x23, 0x39, 0x15, 0xa4, 0x5c, 0xc8, 0x8e, 0x85, 0x78, 0x57, 0x10, 0xd5, 0x3c, 0xfb, 0xf6, 0x90,
	0x89, 0x63, 0xb5, 0x77, 0x13, 0x46, 0x17, 0xe2, 0xf7, 0xb4, 0x4a, 0xa8, 0x50, 0x45, 0xc9, 0xed,
	0x81, 0xe4, 0xb7, 0x82, 0xad, 0xb8, 0xc2, 0xfb, 0xea, 0x71, 0x41, 0x78, 0xd7, 0xf5, 0xd9, 0x81,
	0xb1, 0xc3, 0x89, 0x3c, 0x65, 0x44, 0x46, 0x09, 0x17, 0x98, 0x16, 0xaa, 0xe0, 0xe6, 0xaf, 0x01,
	0x4c, 0xa3, 0x12, 0xe7, 0x1c, 0x27, 0x22, 0x63, 0xf9, 0xcf, 0x84, 0x73, 0x7c, 0x20, 0xaf, 0xd1,
	0x03, 0x98, 0x49, 0x49, 0xb0, 0x20, 0x71, 0xdb, 0x61, 0x6b, 0x8e, 0x36, 0x37, 0x5f, 0xcd, 0x5c,
	0x25, 0xe7, 0xf6, 0x72, 0x6e, 0xd4, 0xcb, 0x2d, 0xa7, 0x75, 0xe3, 0x8c, 0xd1, 0xb0, 0x24, 0x6f,
	0xa3, 0x8c, 0xa6, 0x8a, 0x0c, 0x40, 0x69, 0xb4, 0x55, 0xe8, 0x07, 0xd0, 0x05, 0x8b, 0x53, 0x2c,
	0x88, 0x7d, 0x26, 0xd5, 0x26, 0xbd, 0x9a, 0xfc, 0xca, 0x7b, 0x2c, 0xc8, 0x72, 0x58, 0x37, 0x8e,
	0x31, 0xd3, 0x4b, 0xf2, 0xb6, 0x85, 0xc1, 0x95, 0x60, 0xed, 0x89, 0xe6, 0x30, 0x28, 0x68, 0x12,
	0xe7, 0x98, 0x12, 0xfb, 0xdc, 0xd1, 0xe6, 0x86, 0x2a, 0x04, 0xbd, 0xa0, 0x89, 0x8f, 0x29, 0x09,
	0xfa, 0x00, 0xfd, 0x08, 0xe3, 0x34, 0xe3, 0x09, 0xab, 0x72, 0x11, 0x63, 0xda, 0x1e, 0xf6, 0x85,
	0xa3, 0xcd, 0xcf, 0x97, 0x1f, 0xd7, 0x8d, 0x63, 0xc1, 0x28, 0xcd, 0xb8, 0xd7, 0xb2, 0x77, 0x32,
	0x17, 0x8c, 0xfa, 0x62, 0x85, 0xd1, 0x37, 0x00, 0xa2, 0x1d, 0x46, 0x9c, 0xb0, 0x94, 0xd8, 0x97,
	0xf2, 0x2a, 0x54, 0x37, 0xce, 0x08, 0xae, 0x25, 0xbf, 0x2a, 0x4b, 0x8f, 0xa5, 0x24, 0x30, 0x24,
	0x6a, 0x43, 0x24, 0x60, 0xda, 0xb5, 0x1c, 0x71, 0x79, 0x20, 0x31, 0x17, 0x58, 0x54, 0xdc, 0xbe,
	0x72, 0xb4, 0xf9, 0xe8, 0xd5, 0xd7, 0x6e, 0x6b, 0xb9, 0xfb, 0x1f, 0x03, 0x56, 0x9c, 0x27, 0x7b,
	0x42, 0xd9, 0xb2, 0xfc, 0xa4, 0x6e, 0x9c, 0x29, 0x4c, 0xc4, 0xfb, 0x89, 0xe0, 0x43, 0x0a, 0x7d,
	0x0f, 0xc3, 0x7e, 0x6f, 0xd4, 0x58, 0xf4, 0xe7, 0x6f, 0xed, 0x53, 0x72, 0x36, 0xff, 0x42, 0xe8,
	0x17, 0x30, 0x2a, 0x4e, 0xca, 0x38, 0xcb, 0x1f, 0x99, 0x3d, 0x90, 0x3e, 0xdc, 0xbc, 0xfc, 0xc8,
	0x1d, 0x27, 0xe5, 0x26, 0x7f, 0x64, 0xcb, 0x51, 0xdd, 0x38, 0x00, 0x83, 0xaa, 0xc3, 0xc1, 0x3f,
	0x11, 0xfa, 0x0d, 0xae, 0x13, 0x46, 0x0b, 0x9c, 0xbf, 0x53, 0x9a, 0x86, 0xd4, 0xfc, 0xe2, 0x65,
	0x4d, 0x4f, 0x55, 0x4b, 0xd9, 0x49, 0xdd, 0x38, 0x43, 0x30, 0x93, 0x27, 0x2a, 0x78, 0x0e, 0x90,
	0x0b, 0x90, 0x09, 0x42, 0x63, 0xe9, 0x91, 0x0d, 0x8e, 0x36, 0xbf, 0x5c, 0x8e, 0xeb, 0xc6, 0x31,
	0xc1, 0x68, 0x79, 0x69, 0x65, 0xf0, 0x14, 0xce, 0x0a, 0x18, 0xf4, 0x4f, 0x46, 0x9f, 0xc3, 0x25,
	0xa1, 0x38, 0x3b, 0xc9, 0xdd, 0x35, 0x96, 0x66, 0xdd, 0x38, 0x7a, 0x47, 0x05, 0xea, 0x40, 0x5f,
	0xc2, 0x65, 0x71, 0x64, 0xb9, 0x5a, 0x48, 0xa3, 0x7f, 0x8d, 0xa4, 0xfc, 0x8a, 0xee, 0x49, 0x19,
	0xa8, 0x3c, 0xb2, 0x41, 0xc7, 0x69, 0x5a, 0x12, 0xce, 0xd5, 0xfe, 0x05, 0x3d, 0x9c, 0xfd, 0xa9,
	0x81, 0xf9, 0xec, 0x8b, 0x10, 0x82, 0x0b, 0xe9, 0x87, 0xbc, 0x34, 0x90, 0x31, 0xfa, 0x14, 0x80,
	0x1f, 0x59, 0xd9, 0x39, 0x25, 0xef, 0x0a, 0x0c, 0xc9, 0x48, 0x4b, 0x7c, 0x35, 0xd7, 0x76, 0x7c,
	0x52, 0xfd, 0xff, 0x39, 0xd2, 0x8d, 0x41, 0xfa, 0xe0, 0xaf, 0xd7, 0x2c, 0xd0, 0x3b, 0x4b, 0x6e,
	0xde, 0xc0, 0xe4, 0x83, 0xe5, 0x42, 0x53, 0x18, 0x47, 0x5e, 0x18, 0xef, 0xfc, 0xf0, 0x61, 0xe5,
	0x6d, 0xd6, 0x9b, 0xd5, 0xbd, 0xf5, 0x11, 0xba, 0x86, 0x41, 0x4b, 0x3e, 0xdc, 0x6d, 0xee, 0x2d,
	0x0d, 0x8d, 0x00, 0x54, 0x89, 0xc4, 0x67, 0x68, 0x0c, 0xa6, 0xcc, 0xae, 0xfc, 0xfb, 0x8d, 0xff,
	0x93, 0x75, 0xfe, 0xd5, 0xaf, 0x60, 0x4a, 0xe1, 0x4e, 0x12, 0xc1, 0x28, 0x7a, 0x5f, 0xd1, 0x04,
	0x3d, 0x0a, 0xe3, 0xf5, 0xdd, 0x66, 0x6b, 0x69, 0x68, 0x02, 0xc3, 0x28, 0x8c, 0xc3, 0x9d, 0xe7,
	0xad, 0xc2, 0x70, 0xbd, 0xdb, 0x5a, 0x67, 0x08, 0xe0, 0x2a, 0x0a, 0xe3, 0xbb, 0xed, 0xd6, 0x3a,
	0xef, 0x62, 0x7f, 0xf5, 0xc6, 0xba, 0xd8, 0x5f, 0xa9, 0x1f, 0xe5, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x51, 0x0b, 0x26, 0x7b, 0x38, 0x05, 0x00, 0x00,
}
