// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: es.proto

package es_proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type FieldEs struct {
	Es                   string   `protobuf:"bytes,1,opt,name=es,proto3" json:"es,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldEs) Reset()         { *m = FieldEs{} }
func (m *FieldEs) String() string { return proto.CompactTextString(m) }
func (*FieldEs) ProtoMessage()    {}
func (*FieldEs) Descriptor() ([]byte, []int) {
	return fileDescriptor_718db5c20d0f3738, []int{0}
}
func (m *FieldEs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldEs.Unmarshal(m, b)
}
func (m *FieldEs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldEs.Marshal(b, m, deterministic)
}
func (m *FieldEs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldEs.Merge(m, src)
}
func (m *FieldEs) XXX_Size() int {
	return xxx_messageInfo_FieldEs.Size(m)
}
func (m *FieldEs) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldEs.DiscardUnknown(m)
}

var xxx_messageInfo_FieldEs proto.InternalMessageInfo

func (m *FieldEs) GetEs() string {
	if m != nil {
		return m.Es
	}
	return ""
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldEs)(nil),
	Field:         66664,
	Name:          "es_proto.field",
	Tag:           "bytes,66664,opt,name=field",
	Filename:      "es.proto",
}

func init() {
	proto.RegisterType((*FieldEs)(nil), "es_proto.FieldEs")
	proto.RegisterExtension(E_Field)
}

func init() { proto.RegisterFile("es.proto", fileDescriptor_718db5c20d0f3738) }

var fileDescriptor_718db5c20d0f3738 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x2d, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x2d, 0x8e, 0x07, 0xb3, 0xa4, 0x14, 0xd2, 0xf3, 0xf3,
	0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xbc, 0xa4, 0xd2, 0x34, 0xfd, 0x94, 0xd4, 0xe2, 0xe4, 0xa2, 0xcc,
	0x82, 0x92, 0xfc, 0x22, 0x88, 0x5a, 0x25, 0x49, 0x2e, 0x76, 0xb7, 0xcc, 0xd4, 0x9c, 0x14, 0xd7,
	0x62, 0x21, 0x3e, 0x2e, 0xa6, 0xd4, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xd4,
	0x62, 0x2b, 0x0f, 0x2e, 0xd6, 0x34, 0x90, 0x94, 0x90, 0xac, 0x1e, 0xc4, 0x18, 0x3d, 0x98, 0x31,
	0x7a, 0x60, 0x2d, 0xfe, 0x05, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x12, 0x2f, 0x3a, 0x58, 0x14, 0x18,
	0x35, 0xb8, 0x8d, 0x04, 0xf5, 0x60, 0xf6, 0xea, 0x41, 0x8d, 0x0c, 0x82, 0x18, 0xe0, 0xc4, 0x15,
	0x05, 0x77, 0x5c, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x84, 0xa6, 0x23,
	0x67, 0xaf, 0x00, 0x00, 0x00,
}
